SELECT id,
name,
creator_id,
create_time,
updator_id,
update_time,
staff_id,
begin_date,
end_date,
project_id,
project_name,
project_no,
apply_date,
work_id,
apply_workload,
work_content_desc,
work_apply_state,
audit_staff_id,
work_apply_type,
product_line,warn_type,
warn_ignore_notes,
flow_code,
audit_manager_staff_id,
audit_director_staff_id,
audit_officer_staff_id,
resolve_issues,
associated_project_id 
from temp_lcdp_staff_work_apply 
where 
work_id in (<foreach collection="ids.split(',')" item="id" separator=", ">${@java.lang.Long@parseLong(id)}</foreach>)